version: '3.8'

services:
  jobs:
    hostname: 'jobs'
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app:deleated'
      - '/app/node_modules'
